/* ── Mock data for Last Penny ──────────────────────────────────── */

export const mockMenuItems = [
  {
    _id: "m1",
    name: "Patatas Bravas",
    description: "Çıtır patates, acı sos ve aioli ile servis edilir",
    price: 180,
    category: "yemek" as const,
    image: "/mock/patatas.jpg",
    isAvailable: true,
    isFeatured: true,
  },
  {
    _id: "m2",
    name: "Nachos Grande",
    description: "Cheddar sos, jalapeño, guacamole ve salsa ile",
    price: 220,
    category: "yemek" as const,
    image: "/mock/nachos.jpg",
    isAvailable: true,
    isFeatured: true,
  },
  {
    _id: "m3",
    name: "Bruschetta",
    description: "Domates, fesleğen, sarımsak ve zeytinyağı ile",
    price: 150,
    category: "yemek" as const,
    image: "/mock/bruschetta.jpg",
    isAvailable: true,
    isFeatured: false,
  },
  {
    _id: "m4",
    name: "Tavuk Kanatları",
    description: "Buffalo sos ile marine edilmiş çıtır kanatlar",
    price: 200,
    category: "yemek" as const,
    image: "/mock/wings.jpg",
    isAvailable: true,
    isFeatured: false,
  },
  {
    _id: "m5",
    name: "Halloumi Salatası",
    description: "Izgara hellim, roka, nar ekşisi ve ceviz ile",
    price: 190,
    category: "yemek" as const,
    image: "/mock/salad.jpg",
    isAvailable: true,
    isFeatured: false,
  },
  {
    _id: "m6",
    name: "Sangria",
    description: "Ev yapımı kırmızı şarap, mevsim meyveleri ile",
    price: 160,
    category: "kokteyl" as const,
    image: "/mock/sangria.jpg",
    isAvailable: true,
    isFeatured: true,
  },
  {
    _id: "m7",
    name: "Old Fashioned",
    description: "Bourbon, Angostura bitter, şeker, portakal kabuğu",
    price: 250,
    category: "kokteyl" as const,
    image: "/mock/oldfashioned.jpg",
    isAvailable: true,
    isFeatured: true,
  },
  {
    _id: "m8",
    name: "Mojito",
    description: "Beyaz rom, nane, lime, soda ve şeker ile",
    price: 200,
    category: "kokteyl" as const,
    image: "/mock/mojito.jpg",
    isAvailable: true,
    isFeatured: false,
  },
  {
    _id: "m9",
    name: "Aperol Spritz",
    description: "Aperol, prosecco ve soda ile ferahlatıcı",
    price: 220,
    category: "kokteyl" as const,
    image: "/mock/aperol.jpg",
    isAvailable: true,
    isFeatured: false,
  },
  {
    _id: "m10",
    name: "Efes Draft",
    description: "Soğuk, taze çekimli fıçı bira 50cl",
    price: 120,
    category: "icecek" as const,
    image: "/mock/beer.jpg",
    isAvailable: true,
    isFeatured: false,
  },
  {
    _id: "m11",
    name: "IPA Craft Bira",
    description: "Yerel mikro bira fabrikasından IPA",
    price: 160,
    category: "icecek" as const,
    image: "/mock/ipa.jpg",
    isAvailable: true,
    isFeatured: true,
  },
  {
    _id: "m12",
    name: "Açık Büfe Kahvaltı",
    description: "Cumartesi-Pazar 10:00-15:00 arası zengin kahvaltı",
    price: 350,
    category: "kahvalti" as const,
    image: "/mock/breakfast.jpg",
    isAvailable: true,
    isFeatured: true,
  },
  {
    _id: "m13",
    name: "Cheesecake",
    description: "New York usulü cheesecake, orman meyveli sos",
    price: 130,
    category: "tatli" as const,
    image: "/mock/cheesecake.jpg",
    isAvailable: true,
    isFeatured: false,
  },
  {
    _id: "m14",
    name: "Brownie",
    description: "Sıcak çikolatalı brownie, vanilyalı dondurma ile",
    price: 140,
    category: "tatli" as const,
    image: "/mock/brownie.jpg",
    isAvailable: true,
    isFeatured: false,
  },
];

export const mockEvents = [
  {
    _id: "e1",
    title: "Jazz Night — Ankara Jazz Quartet",
    description:
      "Ankara'nın en iyi jazz müzisyenleri ile unutulmaz bir gece. Klasik jazz standartları ve modern yorumlar.",
    date: "2026-06-05T21:00:00",
    time: "21:00",
    image: "/mock/jazz.jpg",
    category: "jazz" as const,
    isFeatured: true,
  },
  {
    _id: "e2",
    title: "Ayyuka Live",
    description:
      "Türk alternatif rock sahnesinin sevilen grubu Ayyuka, Last Penny sahnesinde!",
    date: "2026-06-07T22:00:00",
    time: "22:00",
    image: "/mock/rock.jpg",
    category: "rock" as const,
    isFeatured: true,
  },
  {
    _id: "e3",
    title: "Akustik Cuma",
    description:
      "Her Cuma akşamı akustik performanslar. Sakin bir atmosferde müzik keyfi.",
    date: "2026-06-06T20:30:00",
    time: "20:30",
    image: "/mock/acoustic.jpg",
    category: "acoustic" as const,
    isFeatured: true,
  },
  {
    _id: "e4",
    title: "DJ Night — Deep House Sessions",
    description:
      "Deep house ve electronic müzik ile dans pistini ısıtıyoruz.",
    date: "2026-06-08T23:00:00",
    time: "23:00",
    image: "/mock/dj.jpg",
    category: "dj" as const,
    isFeatured: false,
  },
  {
    _id: "e5",
    title: "Kitap Kulübü",
    description:
      "Aylık kitap buluşmamız. Bu ay: Sabahattin Ali - Kürk Mantolu Madonna",
    date: "2026-06-10T19:00:00",
    time: "19:00",
    image: "/mock/bookclub.jpg",
    category: "talk" as const,
    isFeatured: false,
  },
  {
    _id: "e6",
    title: "Stand-Up Comedy Night",
    description:
      "Ankara'nın en komik stand-up'çıları ile kahkaha dolu bir gece.",
    date: "2026-06-12T21:00:00",
    time: "21:00",
    image: "/mock/standup.jpg",
    category: "other" as const,
    isFeatured: false,
  },
];

export const mockProducts = [
  {
    _id: "p1",
    name: "Last Penny Classic Tee",
    description: "Siyah pamuklu tişört, ön yüzde Last Penny logosu",
    price: 350,
    category: "tshirt" as const,
    image: "/mock/tshirt1.jpg",
    sizes: ["S", "M", "L", "XL"],
    stock: 50,
  },
  {
    _id: "p2",
    name: "Jazz Night Tee",
    description: "Özel jazz night serisi, limited edition baskı",
    price: 400,
    category: "tshirt" as const,
    image: "/mock/tshirt2.jpg",
    sizes: ["S", "M", "L", "XL"],
    stock: 25,
  },
  {
    _id: "p3",
    name: "Last Penny Hoodie",
    description: "Siyah kapüşonlu sweatshirt, sırt baskılı",
    price: 650,
    category: "hoodie" as const,
    image: "/mock/hoodie.jpg",
    sizes: ["S", "M", "L", "XL"],
    stock: 30,
  },
  {
    _id: "p4",
    name: "Last Penny Şapka",
    description: "Siyah beyzbol şapka, işlemeli logo",
    price: 200,
    category: "cap" as const,
    image: "/mock/cap.jpg",
    sizes: ["Standart"],
    stock: 40,
  },
  {
    _id: "p5",
    name: "Bardak Altlığı Seti",
    description: "4'lü ahşap bardak altlığı seti, lazer baskılı",
    price: 150,
    category: "accessory" as const,
    image: "/mock/coaster.jpg",
    sizes: ["Standart"],
    stock: 60,
  },
  {
    _id: "p6",
    name: "Last Penny Anahtarlık",
    description: "Metal penny coin anahtarlık, antik bakır kaplama",
    price: 100,
    category: "accessory" as const,
    image: "/mock/keychain.jpg",
    sizes: ["Standart"],
    stock: 100,
  },
];

export const mockOrders = [
  {
    _id: "o1",
    userId: "u1",
    userName: "Ahmet Yılmaz",
    items: [
      { productId: "p1", name: "Last Penny Classic Tee", quantity: 2, size: "L", price: 350 },
      { productId: "p4", name: "Last Penny Şapka", quantity: 1, size: "Standart", price: 200 },
    ],
    totalPrice: 900,
    status: "delivered" as const,
    createdAt: "2026-05-20T14:30:00",
  },
  {
    _id: "o2",
    userId: "u2",
    userName: "Elif Kaya",
    items: [
      { productId: "p3", name: "Last Penny Hoodie", quantity: 1, size: "M", price: 650 },
    ],
    totalPrice: 650,
    status: "shipped" as const,
    createdAt: "2026-05-25T09:15:00",
  },
  {
    _id: "o3",
    userId: "u3",
    userName: "Mehmet Demir",
    items: [
      { productId: "p2", name: "Jazz Night Tee", quantity: 1, size: "XL", price: 400 },
      { productId: "p6", name: "Last Penny Anahtarlık", quantity: 2, size: "Standart", price: 100 },
    ],
    totalPrice: 600,
    status: "confirmed" as const,
    createdAt: "2026-05-28T16:45:00",
  },
  {
    _id: "o4",
    userId: "u4",
    userName: "Zeynep Arslan",
    items: [
      { productId: "p1", name: "Last Penny Classic Tee", quantity: 1, size: "S", price: 350 },
      { productId: "p5", name: "Bardak Altlığı Seti", quantity: 1, size: "Standart", price: 150 },
    ],
    totalPrice: 500,
    status: "pending" as const,
    createdAt: "2026-05-30T11:20:00",
  },
  {
    _id: "o5",
    userId: "u5",
    userName: "Can Özkan",
    items: [
      { productId: "p3", name: "Last Penny Hoodie", quantity: 1, size: "L", price: 650 },
      { productId: "p4", name: "Last Penny Şapka", quantity: 1, size: "Standart", price: 200 },
    ],
    totalPrice: 850,
    status: "pending" as const,
    createdAt: "2026-05-31T08:00:00",
  },
];

export const mockDashboardStats = {
  totalRevenue: 14500,
  totalOrders: 23,
  totalUsers: 156,
  totalMenuItems: 14,
  totalEvents: 6,
  totalProducts: 6,
  revenueByMonth: [
    { month: "Oca", revenue: 8200 },
    { month: "Şub", revenue: 9500 },
    { month: "Mar", revenue: 11200 },
    { month: "Nis", revenue: 10800 },
    { month: "May", revenue: 14500 },
    { month: "Haz", revenue: 12300 },
  ],
  ordersByStatus: [
    { status: "Beklemede", count: 5 },
    { status: "Onaylandı", count: 4 },
    { status: "Kargoda", count: 8 },
    { status: "Teslim", count: 6 },
  ],
  popularItems: [
    { name: "Last Penny Classic Tee", orders: 45 },
    { name: "Last Penny Hoodie", orders: 32 },
    { name: "Jazz Night Tee", orders: 28 },
    { name: "Last Penny Şapka", orders: 22 },
    { name: "Bardak Altlığı Seti", orders: 18 },
  ],
  recentActivity: [
    { type: "order", message: "Yeni sipariş: Can Özkan — ₺850", time: "2 saat önce" },
    { type: "user", message: "Yeni üye: Deniz Yılmaz", time: "5 saat önce" },
    { type: "event", message: "Etkinlik güncellendi: Jazz Night", time: "1 gün önce" },
    { type: "order", message: "Sipariş teslim edildi: #o1", time: "2 gün önce" },
    { type: "menu", message: "Menüye eklendi: Aperol Spritz", time: "3 gün önce" },
  ],
};
